### ISSUE TITLE
[테코톡] 인터페이스 | 알파

### ISSUE THREAD

**Issue by sinb57** [woowacourse/media#10]

**Comment by sinb57** [comment]
영상 편집 끝냈습니다~
https://drive.google.com/file/d/1WQ3zumwThmSj57TYfLW_-VSx0Im4mpl6/view?usp=sharing

**Comment by ldk980130** [comment]
[편집본 폴더](https://drive.google.com/drive/folders/1FR0V0lDfSHtw0fq6A74CzS6QXwj_J6wZ)에 영상과 자막 모두 올려놓았습니다~

**Comment by sinb57** [comment]
고생 많으셨습니다~!!!
