### ISSUE TITLE
[브이로그] 공책팀 브이로그를 업로드한다.

### ISSUE THREAD

**Issue by intae92** [woowacourse/media#108]
공책팀 브이로그 편집 완료 했고 썸네일과 함께 업로드 했습니다.
영상 근로 > 브이로그 > 공책vlog에 파일 위치시켜 뒀습니다!

[공책팀 브이로그](https://drive.google.com/drive/folders/157HVM1v9sXAEZk-O7Q4hz9vc82_Lg3L9)

업로드 하시면 될 것 같습니다!

**Comment by woowabrie** [comment]
마지막에 노래방에서 노는거 보고 빵터졌네요 ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ
내일 18시 공개로 설정해뒀습니다.
https://youtu.be/cKs1glgkNrY

고생 많으셨어요~
