### ISSUE TITLE
[테코톡] this | 하리

### ISSUE THREAD

**Issue by ronci** [woowacourse/media#12]

**Comment by intae92** [comment]
영상 편집 했습니다
https://drive.google.com/drive/folders/1ihDyCgw9VndMuhztdDfTfBN_ccUo1WKz

**Comment by ronci** [comment]
편집 + 자막 완료했습니다!
https://drive.google.com/drive/folders/1ihDyCgw9VndMuhztdDfTfBN_ccUo1WKz
