### ISSUE TITLE
[우테뷰] 왼손 코치 인터뷰 영상을 업로드한다.

### ISSUE THREAD

**Issue by OzRagwort** [woowacourse/media#128]
<img width="1349" alt="image" src="https://user-images.githubusercontent.com/32123302/190958120-8043db46-5d7f-4ee7-b814-8b3a0d534839.png">

편집, 자막, 썸네일까지 완료되었습니다.

업로드 부탁드립니다!

[구글 드라이브 링크](https://drive.google.com/drive/folders/1-5K9JZaAIG_qOC3jsk8iF5csxicO3f-X)

**Comment by woowabrie** [comment]
9월 26일 월요일 6시에 공개 예약했습니다.

https://www.youtube.com/watch?v=Iy1XWtaxvAc
