### ISSUE TITLE
[테코톡] 람다 | 스컬

### ISSUE THREAD

**Issue by sojukang** [woowacourse/media#13]

**Comment by sojukang** [comment]
[편집본 링크](https://drive.google.com/drive/folders/1FR0V0lDfSHtw0fq6A74CzS6QXwj_J6wZ)
안녕하세요 [쿤](@Hongdonggeon) 🌟 반갑습니다. 
4분 13초 경 영상의 네트워크 끊김 문제로 몇 초 잘라낸 것 빼고는 앞 뒤만 잘랐습니다👍.

**Comment by Hongdonggeon** [comment]
넵 편집 수고하셨습니다!! 자막 처리 완료해서 편집본 링크에 올려두었어요!!
