### ISSUE TITLE
[우테뷰] 프롤로그 근로팀 인터뷰 영상을 업로드한다.

### ISSUE THREAD

**Issue by OzRagwort** [woowacourse/media#130]
<img width="1179" alt="image" src="https://user-images.githubusercontent.com/32123302/190959268-84a2f1eb-d2c3-4252-8ec9-a5d2348f00ac.png">

편집, 자막, 썸네일까지 완료되었습니다.

업로드 부탁드립니다!

[구글 드라이브 링크](https://drive.google.com/drive/folders/1-4-bAWEAbpNqVlumr2HCBgfoTLzrog7z)

**Comment by woowabrie** [comment]
10/12 6시 공개 예약 해뒀습니다.
