### ISSUE TITLE
[행사] 데모데이 현장스케치 영상을 업로드한다.

### ISSUE THREAD

**Issue by ldk980130** [woowacourse/media#132]
작업 완료했습니다!
https://drive.google.com/drive/folders/1ozeLTyr2iXsksZsR5hTkMU4Lm-dZb6rW

**Comment by sinb57** [comment]
될지는 모르겠지만 https://woowahan.zoom.us/j/95290115585?pwd=VDB5NXN5QnlLTStuZUtBVDQrMW4yQT09 링크로 들어가보시겠어요?

**Comment by woowabrie** [comment]
9월 30일 업로드 되어 클로즈 할게요
