### ISSUE TITLE
[브이로그] 모아모아팀 브이로그 영상을 업로드한다.

### ISSUE THREAD

**Issue by tco0427** [woowacourse/media#133]
<img width="1099" alt="모아모아vlog썸네일" src="https://user-images.githubusercontent.com/57028386/192440984-068b3bad-3036-401c-918a-3d7c8fd2b7aa.png">

영상 제작 및 썸네일 작업 완료하였습니다!
업로드 요청드립니다~_~

[영상 및 썸네일 링크](https://drive.google.com/drive/folders/1domLIn-Qe_GPptnlIgz84BZ9TL97MfYf)

**Comment by woowabrie** [comment]
10/19 6시 공개로 예약해뒀습니다.

**Comment by tco0427** [comment]
감사합니당~_~
