### ISSUE TITLE
[우테뷰] 브랜딩 근로팀 인터뷰 영상을 업로드한다.

### ISSUE THREAD

**Issue by OzRagwort** [woowacourse/media#136]
<img width="1201" alt="image" src="https://user-images.githubusercontent.com/32123302/193728673-57f71183-236a-4912-b9ee-35e0709d16e9.png">

편집, 자막, 썸네일까지 완료되었습니다.

업로드 부탁드립니다!

[구글 드라이브 링크](https://drive.google.com/drive/folders/1YqV9MrHwM86uqJU2JnEXEVwcKqAWCos8)

**Comment by sinb57** [comment]
https://woowahan.zoom.us/j/96586914683?pwd=N1pWR1NkVENRbjZQbzVsWjJNaVBkZz09

**Comment by woowabrie** [comment]
10/26 6시 예약 했습니다.
