### ISSUE TITLE
[데모데이] 데모데이 썸네일에 팀컬러를 적용한다

### ISSUE THREAD

**Issue by sinb57** [woowacourse/media#140]
## 회의 안건 
테코톡 영상 썸네일과 데모데이 영상 썸네일 배경이 동일하여, 유튜브상에서 영상 구분이 되지 않는다!!
따라서 데모데이 영상 썸네일 배경에 팀컬러를 적용하여 차별을 두도록 하자!!

## 진행사항
슬랙 채널을 통해 팀컬러를 조사했으며, 그 내용은 아래와 같습니다!

팀 | 컬러 | 비고 
-- | -- | --
스모디 | RGBA(123, 97, 255, 0.5) |  
속닥속닥 | RGBA(51, 210, 164, 0.5) |  
회고덕 | RGBA(49, 113, 114, 0.35) | #31717259
달록 | RGBA(244, 189, 104, 0.5) |  
꼭꼭 | RGBA(255, 112, 32, 0.5) | #FF702080
모아모아 | RGBA(82, 75, 168, 0.5) |  
땡쿠 | RGBA(255, 99, 71, 0.5) |  
공책 | RGBA(104, 193, 248, 0.5) | #68C1F880
F12 | RGBA(246, 190, 190, 0.5) | #F6BEBE80
체크메이트 | RGBA(247, 227, 153, 0.5) |  
티타임 | RGBA(204, 230, 186, 0.5) | #CCE6BA80
내편 | RGBA(152, 218, 255, 0.5) | #98DAFF80
모락 | RGBA(248, 200, 70, 0.5) | #F8C84680
공식 | RGBA(252, 234, 191, 0.5) | #FCEABF80
레벨로그 | RGBA(94, 167, 181, 0.5) | #5EA7B580
줍줍 | RGBA(255, 153, 0, 0.5) | #FF990080
터놓고 | RGBA(255, 56, 92, 0.5) |  
모두모여라 | RGBA(0, 70, 127, 0.5) | #00467F80

</br>

위 내용을 반영하여 임시 제작한 ppt 및 pdf는 다음과 같습니다!!
~ppt : https://docs.google.com/presentation/d/1n45EzRV07E-zVXdeDb0s5zXZIGtr4f4I/edit?usp=sharing&ouid=110421532298402852592&rtpof=true&sd=true~
~pdf : https://drive.google.com/file/d/12xmQvXI7wHHvTVLyBFDocgYQgifc8oCk/view?usp=sharing~
(겹치는 색상을 확인하기 편하게, 유사 색상 순으로 배치하였습니다~)

</br>

pdf 파일을 크루들에게 공개하여 피드백을 물었으며, 현재까지 연락받은 피드백이 없기에 해당 사항으로 썸네일 작업을 진행하겠습니다~~

---

++ 2022-10-12) 작업 완료 (아래 코멘트 작성)

**Comment by sinb57** [comment]
1차 ~ 5차 데모데이 썸네일 작업 완료했습니다~!!
https://drive.google.com/drive/folders/13nXbo1JMD6GwMfwLptNjLseXBPOByTKe?usp=sharing

++특이사항) 줍줍 팀의 경우, 5차데모데이 이후부터 썸네일 인원이 한명 감소했습니다

**Comment by wmakerjun** [comment]
썸네일 유튜브에 반영 완료하였습니다 😄
