### ISSUE TITLE
[우테뷰] F12팀 인터뷰 영상을 업로드한다.

### ISSUE THREAD

**Issue by OzRagwort** [woowacourse/media#146]
<img width="1389" alt="image" src="https://user-images.githubusercontent.com/32123302/196048947-4f96dfd6-3e04-47ee-964e-a06afdf5c78f.png">

편집, 자막, 썸네일 완료되었습니다!

[드라이브 링크](https://drive.google.com/drive/folders/1smqXOrkPyhGDzUYoYN62CgEnhbv4yaUg)

**Comment by woowabrie** [comment]
@OzRagwort 
업로드 하다보니 썸네일이 이전에 근로 팀과 동일한 포맷인데요.
F12팀이 근로 팀처럼 보이는게 아닐까 조금 우려되네요. 혹시 의도하신건가요?

**Comment by OzRagwort** [comment]
@woowabrie 
다른 인터뷰는 영상 소스 중간을 캡쳐를 하는 식으로 대체했는데 이번 영상은 그렇게 하기가 조금 애매한 것 같아서 저런식으로 만들었습니다
지금 다시보니 근로팀처럼 보일 수도 있을 것 같네요! 
데모데이 썸네일 형식처럼 수정해보려는데 괜찮을까요?

**Comment by woowabrie** [comment]
@OzRagwort 
네 좋습니다! 빠른 확인 감사해요 알린

**Comment by OzRagwort** [comment]
@woowabrie 
안녕하세요 브리 ! F12팀에게 단체 사진을 받아서 썸네일을 다시 만들어 봤습니다! 팀 데모데이처럼 만들면 또 데모데이랑 비슷해져서 아래처럼 썸네일을 만들어봤는데 괜찮을까요?

<img width="1391" alt="image" src="https://user-images.githubusercontent.com/32123302/201039340-19a4373d-ded1-4089-b209-33a513076754.png">

**Comment by woowabrie** [comment]
오늘 18시에 공개 예약 했습니다.
