### ISSUE TITLE
[테코톡] Parameter와 Argument | 포키

### ISSUE THREAD

**Issue by sinb57** [woowacourse/media#16]

**Comment by sinb57** [comment]
영상 편집 끝냈습니다~
https://drive.google.com/file/d/1S46vMzp_-i4V0i1qcXKDrlw99Etu5TwG/view?usp=sharing

**Comment by ldk980130** [comment]
자막까지 모두 완료했습니다!
[편집본](https://drive.google.com/drive/folders/1UWmGz0-MDZcuW7hxfY9deRnImwlqSbPt)
