### ISSUE TITLE
[브이로그] 마지막 브이로그 영상을 기획한다.

### ISSUE THREAD

**Issue by Byeongju-Kong** [woowacourse/media#160]

**Comment by tco0427** [comment]
**질문 목록** 
- 우아한테코크스 이전의 나와 지금의 나를 비교해본다면(2명)
- 가장 기억에 남는 순간(3명)
- 아쉬운 순간(3명)
- 코치님께 한마디(4명)
- 함께 한 크루들에게 한마디(4명)
- 앞으로 어떤 개발자가 되고 싶은지(3명)
