### ISSUE TITLE
[우테뷰] 지원플랫폼 근로 팀 인터뷰 영상을 업로드한다

### ISSUE THREAD

**Issue by OzRagwort** [woowacourse/media#170]
@wmakerjun @woowabrie
안녕하세요 준, 브리! 지원플랫폼 근로 팀 인터뷰 영상 편집이 끝났습니다.

[드라이브 링크](https://drive.google.com/drive/folders/1DzRgXI39pE32H8pj_MI8UJjicqse94_8)

업로드 부탁드리겠습니다!

<img width="1369" alt="image" src="https://user-images.githubusercontent.com/32123302/203266847-a13bc04f-cb68-4699-872e-a730f9320b3e.png">

**Comment by woowabrie** [comment]
11/23 18:00 공개 처리 할게요.
