### ISSUE TITLE
[테코톡] Stream vs for | 크리스, 로마

### ISSUE THREAD

**Issue by sojukang** [woowacourse/media#18]

**Comment by sojukang** [comment]
안녕하세요 [후디](@devHudi)👋👋!!!!
테코톡 진행 중 끊김이나 따로 자를 부분이 없어 앞뒤만 자른 상태입니다. 감사합니다.
[구글 드라이브 링크](https://drive.google.com/drive/folders/1FGZidjzQkSelcc0-NWpv9BUgUxcQSZHH)

**Comment by devHudi** [comment]
자막 작업도 모두 끝났습니다!
[구글 드라이브 링크](https://drive.google.com/drive/folders/1FGZidjzQkSelcc0-NWpv9BUgUxcQSZHH)
