### ISSUE TITLE
[테코톡] 브라우저의 Event Loop - 병민

### ISSUE THREAD

**Issue by Hongdonggeon** [woowacourse/media#19]

**Comment by OzRagwort** [comment]
안녕하세요 [쿤](@Hongdonggeon)

편집이 마무리 되어서 알려드려요

자막 잘 부탁드립니다!

[파일 확인](https://drive.google.com/drive/folders/1aV4ettr3YlYxHCrlwDVRtAXuMgfGEzgS)
