### ISSUE TITLE
[우테뷰] 촬영을 한다 - 5월 2일 오리, 라라

### ISSUE THREAD

**Issue by wmakerjun** [woowacourse/media#2]

**Comment by sure-why-not** [comment]
## 1안 - new 코치 인터뷰

### 필요성
- 아직 강의를 하지 않았거나 데일리에서 만나지 않은 코치분들을 모르는 크루들이 많음
- 외부에서도 우테코 내에서 코치분들이 어떤 역할을 하시는지 알리는 기회
- 프론트 / 백 엔드 서로서로 코치분들을 잘 모름

### 예상 섭외 인물
- 코치 (새로온 분 전부?)
	- 네오
	- 브리
	- 토미
	- 구구
		- 프론트는 어떻게해야할지 모르겠음
		- 4기가 시작되면서 새로온 분이 없음
		- 이거 논의 필요
- 인터뷰어
	- 2명이 인터뷰함
	- 인터뷰어 하고싶은 사람 모집하거나 기획팀에서 인터뷰 예정

### 인터뷰 내용
- 현재 담당하고 있는 업무에 대한 소개 / 역할, 자기소개 등
- 어떻게 코치로 합류하게 되었는지에 대한 내용
- 새로와서 어떤 점이 어색하고 어떤 점이 좋은지
- 온라인으로 진행했었는데 오프라인으로 만난 크루들이 어색하지는 않은지
- 오프라인으로 바뀌면서 우테코 과정에서 느끼는 변화점이 있는지
- 아직 레벨 1인데 인상깊은 크루가 있는지
- 코칭하면서 어떨 때 제일 뿌듯함을 느꼈는지
- 크루들이 우테코에서 가장 얻어가야하는게 어떤 것이 있는지, 어떤걸 안해야되는지

**Comment by sure-why-not** [comment]
## 2안 - 크루 인터뷰

### 필요성
- 자기를 뽐내고 싶어하는 크루가 몇명 있음(유튜브 박제되고싶어함)
- 외부에 왜 우테코에 들어와야하는지를 소개할 수 있음
- 크루들의 솔직한 인터뷰를 통해서 이런 크루도 있구나하고 서로에 대해 친밀해질 수 있음


### 예상 섭외 인물
- 본인들이 직접 찾아옴
	- 호호
	- 스컬
- 프론트도 있으면 좋다라고 생각


### 인터뷰 내용
- 간단한 자기소개
- 우테코에 들어오게 된 동기
- 우테코를 시작하면서 3개월정도되었는데 적응이 되었는지? 요즘은 어떤지?
- 전공인지 비전공인지
	- 비전공이라면 비전공이라서 좋았던점, 힘든점
	- 전공이라면 전공이라서 좋았던점, 힘든점
- 합격 과정이 굉장히 길었는데 어떠셨는지
- 리뷰를 경험해본적이 있는지, 리뷰받으면서 미션하는데 힘든점이 있는지
- 미션을 진행하면서 혹은 우테코 생활하면서 기억에 남는 에피소드
	- 미션에서 기억에 남는 페어, 코드리뷰, 리뷰어 등등
- 우테코를 어떤 마음가짐으로 임하고 있는지
- 우테코를 하기전과 후의 달라진 삶
- 공부만하고 사시나요? 요즘 안노시나요?
- 코딩안하면 뭐하시나요?
- 레벨 1은 온라인으로 진행했고 레벨2는 오프라인으로 전환이 되었는데 어떤 차이가 있는지, 어떤게 더 좋은지
- 포비에게 한마디

**Comment by sure-why-not** [comment]
## 네오 인터뷰
**MC : 오찌, 호호**

- 오찌 : 자기소개 간단하게 부탁드립니다.
	- ~파트 코치를 맡고 있는 ~입니다.
	- 아~ 닉네임을 네오로 지으신 이유가 있나요?
- 코치 업무를 하고 계신다고 하셨는데, 우테코 내에서 구체적으로 어떤 일을 하고 계신가요?
	- 담당하고 있는 업무에 대해서 간단히 소개
---
- 호호 : 현업에서 일을 하다가 어떤 계기로 우테코 코치로 합류하게 되셨나요?
	- 이전에 개발자였다가 합류된 계기 내용
---
- 오찌 : 레벨 1동안 강의를 진행하셨는데, 강의를 그렇게 잘 하셨다고 소문이 자자하더라구요~ 이 부분에 대해 인정하시나요~?
	- 아 킹정하죠.
----
- 호호 : 모든 레벨1 활동을 온라인으로 했었는데 레벨 2부터 오프라인으로 전환되었잖아요~ 오프라인으로 직접 크루들을 만나보니 어떠신가요? 어색하진 않으신가요?
- 그럼 기억에 남는 크루나 에피소드가 있나요?
---
- 오찌 : 코칭을 하시면서 어떨때 가장 뿌듯함을 느끼시나요?
---
- 호호 : 크루들이 우테코에서 얻어갔으면 하는 것 한가지를 뽑자면?
- 그럼 반대로 우테코에서 하지 않았으면 좋겠다! 하는 것이 있나요?
---
- 오찌 : 익명의 제보자가 피부관리를 물어보는데 피부관리 비법이 있나요?
---
- 호호 : 끝으로 레벨 2, 3, 4에서 고통받을 크루들에게 한마디 부탁드립니다.

**Comment by wmakerjun** [comment]
### 편집점 참고 링크
https://docs.google.com/spreadsheets/d/1zLU5xQ10IoJhUaifJ4fmiUUzhjo5TsLMWz9IISiaxzw/edit#gid=0

**Comment by jinyoungchoi95** [comment]
https://drive.google.com/drive/folders/1ImGWlbSo7w3oPKENcVq9SpxBQHgV7UmA
