### ISSUE TITLE
[테코톡] 디바운싱과 쓰로틀링 | 자스민

### ISSUE THREAD

**Issue by intae92** [woowacourse/media#20]

**Comment by intae92** [comment]
영상 편집해서 올렸습니다~~
[https://drive.google.com/drive/folders/1aV4ettr3YlYxHCrlwDVRtAXuMgfGEzgS](https://drive.google.com/drive/folders/1aV4ettr3YlYxHCrlwDVRtAXuMgfGEzgS)

**Comment by ronci** [comment]
자막 편집까지 완료했습니다!
https://drive.google.com/drive/folders/1aV4ettr3YlYxHCrlwDVRtAXuMgfGEzgS
