### ISSUE TITLE
[테코톡] OOP(SOLID) & FP | 필즈, 판다

### ISSUE THREAD

**Issue by sinb57** [woowacourse/media#24]

**Comment by sinb57** [comment]
영상 편집 끝마쳤습니다~
https://drive.google.com/file/d/1xfRWT1mp5bRlq4rpG5NOYKWO7DoM9d6j/view?usp=sharing

**Comment by devHudi** [comment]
자막 추가하였습니다!

https://drive.google.com/drive/folders/1ncJURqee8HDuYPtHYb0xSVLnS0E0Jt-f
