### ISSUE TITLE
[테코톡] Java 11 | 호호

### ISSUE THREAD

**Issue by OzRagwort** [woowacourse/media#25]

**Comment by OzRagwort** [comment]
안녕하세요 [더즈](@ldk980130)

편집이 마무리 되어서 알려드려요

9분 58~10분 정도에 조금 버벅거린 부분 편집한 곳 빼고는 앞뒤만 편집했습니다

자막 잘 부탁드립니다!

[파일 확인](https://drive.google.com/drive/folders/1ncJURqee8HDuYPtHYb0xSVLnS0E0Jt-f)

**Comment by ldk980130** [comment]
자막 추가 완료했습니다~~!!
