### ISSUE TITLE
[테코톡] 비동기 처리 - promise | 안

### ISSUE THREAD

**Issue by ronci** [woowacourse/media#26]

**Comment by intae92** [comment]
영상 편집 했습니다~~
[https://drive.google.com/drive/folders/1BzPGarmOocupNi1CZX34-Pg489cQudU2](https://drive.google.com/drive/folders/1BzPGarmOocupNi1CZX34-Pg489cQudU2)

**Comment by ronci** [comment]
편집 & 자막 편집 완료했습니다!
https://drive.google.com/drive/folders/1BzPGarmOocupNi1CZX34-Pg489cQudU2
