### ISSUE TITLE
[테코톡] 브라우저 렌더링 | 결

### ISSUE THREAD

**Issue by Hongdonggeon** [woowacourse/media#27]

**Comment by sojukang** [comment]
안녕하세요 [쿤](@Hongdonggeon)👋 
앞, 뒤 외는 2분 32초 경 `엔터를 누르면`이 두 번 반복되어 잘라내었습니다. 
Cheer up~ 
[구글 드라이브 링크](https://drive.google.com/drive/folders/1ncJURqee8HDuYPtHYb0xSVLnS0E0Jt-f)
