### ISSUE TITLE
[브이로그] 촬영을 한다 5월 2일 - 크리스, 디우

### ISSUE THREAD

**Issue by wmakerjun** [woowacourse/media#3]

**Comment by Byeongju-Kong** [comment]
# 영상 기획/촬영 1차 회의(vlog)

일자 : 2022.04.25
참여자 : 크리스, 디우


## 백엔드 선릉 크루들의 vlog

- 이번에 처음 개방한 선릉 캠퍼스의 소개 및 크루들의 전반적인 생활 모습을 담기 위함.
- 한 명을 담는 것도 좋지만, 함께 어우러지고, 자유로운 우테코의 분위기를 보여주면 좋을 듯함.

### 선릉 캠퍼스 공간 목록

- 출입문
- 트랙룸
- 거실?
- 창문 쪽 공간
- 큰 강의실
- 작은 강의실
- 페어룸
- 회의실
- 복도에 있는 벽에 붙어 있는 소파
- 코치실

### 구성

처음 시작은, 한강 위를 지나는 지하철 속에서 본 한강 모습 + 제목

1. 크루들의 각자 다른 출근길들(bgm 야무지면서 달달한 걸로)
✔️ 이곳저곳
→ 크루들에게 등교길 영상 부탁하고, 엮으면 좋을 것 같음.
(ex : “아침 등교길이 힘들지만, 크루들을 만나서 함께 공부할 수 있어서 힘이 납니다.”, “오늘 어떤 일을 할 것입니다.)
2. 캠퍼스 입구로 들어오는 크루들의 모습을 촬영
✔️출입문
→ 인사 + 손 흔들어주는 모습 ( 삼각대 설치 및 손을 흔들어돌라고 안내문 작성 )
3. 데일리 미팅 전, 크루들의 모습
✔️ 거실, 복도 쇼파
→ 스몰토크, 개인 학습
4. 데일리 미팅 모습 ( 구구 조 가즈아~ )
✔️ 트랙룸, 거실
5. 강의 모습
✔️ 대강의실
→ **타임 랩스** 활용해도 좋을듯. 근데 촬영해도 되는지 의문. 허락 맡아야 할듯
6. 점심 시간
✔️ 이곳저곳
→ 점심 먹는 크루들( 여러 파티 )
→ 점심 먹고 산책 하는 모습도 담으면 좋을 듯(선릉과 정릉 및 주변 산책로)
7. 페어 프로그래밍 모습 및 개인 공부
✔️ 페어룸, 창문 쪽 공간, 작은 강의실
→ 페어 프로그래밍에 대한 간단한 소개(이래서 좋고, 저래서 좀 힘들다)
8. 코치들의 모습
✔️ 코치사무실
→ 코치들의 업무 모습 및 가벼운 인터뷰
9. 수다 시간 가지는 크루들의 모습
✔️ 거실 및 복도 쇼파
10. 스터디 모습
✔️ 회의실
11. 저녁 먹으로 가거나, 술 마시러 가거나, 집가는 크루들, 남아서 공부하는 크루들의 모습
→ 모습들을 엮으면 좋을 것 같음.

- 선릉 창문 view
- 선릉에 보이는 일몰(보인다면)

**Comment by tco0427** [comment]
[vlog - 구글 드라이브 링크](https://drive.google.com/drive/u/0/folders/1n_4l-L0Fqro4sCaPB0gf2At24RwpLU8e)

**Comment by wmakerjun** [comment]
### 편집점 참고 링크
https://docs.google.com/spreadsheets/d/1zLU5xQ10IoJhUaifJ4fmiUUzhjo5TsLMWz9IISiaxzw/edit#gid=0
