### ISSUE TITLE
[테코톡] HTTP 메서드와 상태 코드 | 코카콜라

### ISSUE THREAD

**Issue by sojukang** [woowacourse/media#34]

**Comment by sojukang** [comment]
안녕하세요 [우연](@ronci)👋👋
중간에 편집이 필요한 부분이 없어서 앞뒤만 잘랐습니다. 
피피티로 발표하실 때는 자막이 영상에 이미 존재합니디.
실습하실 때는 자막이 없는 상태입니다.  
[편집본 링크](https://drive.google.com/drive/folders/1eEAZ-sqheS54O4nBKXW8ePz-eRm_A1w2)

**Comment by ronci** [comment]
코카콜라 자막 및 편집 완료했습니다!
https://drive.google.com/drive/folders/1eEAZ-sqheS54O4nBKXW8ePz-eRm_A1w2

ppt 내부에서 자체적으로 있는 자막부분은 제외하고 자막을 추가했습니다!
