### ISSUE TITLE
[테코톡] IoC, DI, DIP | 오찌, 야호

### ISSUE THREAD

**Issue by sojukang** [woowacourse/media#39]

**Comment by sojukang** [comment]
안녕하세요 [민초](@jswith)👋👋
중간에 딱히 자를만한 부분이 없어서 앞 뒤만 잘른 상태입니다. 
썸네일도 같이 업로드하였습니다. 감사합니다~!!🌟
[편집본 링크](https://drive.google.com/drive/folders/1FbBD9ml-4KRc70wtz2RCcqeexII4xwfB)

**Comment by jswith** [comment]
https://drive.google.com/drive/folders/1FbBD9ml-4KRc70wtz2RCcqeexII4xwfB

최종 영상 편집 + 자막 완료했습니다!
