### ISSUE TITLE
[테코톡] 제네릭 | 그린론

### ISSUE THREAD

**Issue by sinb57** [woowacourse/media#4]

**Comment by sinb57** [comment]
그린론의 테코톡 (제네릭) 영상 편집했습니다~~!!
https://drive.google.com/file/d/1cQqfpjSLDoKWDdvfeLW4pPOhicy3vgXH/view?usp=sharing

**Comment by Hongdonggeon** [comment]
처음 만든 자막파일이 영상이랑 씽크가  안 맞아서 오래 걸렸네요ㅠ 
다시 작업 해서 완료했어요!!
