### ISSUE TITLE
[테코톡] REST API | 정

### ISSUE THREAD

**Issue by devHudi** [woowacourse/media#43]

**Comment by devHudi** [comment]
@jswith 
[드라이브](https://drive.google.com/drive/folders/1_pl1FivkZwtJBXAq8iJF7Cr9Xjf7tXNK)

편집본 업로드 완료했습니다!

**Comment by jswith** [comment]
추가편집 + 자막 완료

https://drive.google.com/drive/folders/1_pl1FivkZwtJBXAq8iJF7Cr9Xjf7tXNK
