### ISSUE TITLE
[우테뷰] 백엔드 리뷰어 인터뷰 영상을 편집한다.

### ISSUE THREAD

**Issue by sure-why-not** [woowacourse/media#46]

**Comment by OzRagwort** [comment]
[드라이브](https://drive.google.com/drive/folders/19jsie6dgWwraWy435wycsLKk6TsM5c-3)

[편집점](https://docs.google.com/spreadsheets/d/1jZfj9JOcWwFdH_BM_yX2uyDAWpHhpzRDn5_vnJekTnE/edit#gid=0)

**Comment by OzRagwort** [comment]
영상 편집, 자막 추가 완료했습니당
