### ISSUE TITLE
[테코톡] Git 브랜칭 전략 | 렉스

### ISSUE THREAD

**Issue by wmakerjun** [woowacourse/media#5]

**Comment by intae92** [comment]
git 브랜치 전략, 렉스 편집 영상 올렸습니다.
https://drive.google.com/drive/folders/14eTH5D4QpXMacfTGaVqlF3pGqyIg7Wng

**Comment by ronci** [comment]
git 브랜치 전략, 렉스 편집 + 자막 영상 올렸습니다!
https://drive.google.com/drive/folders/14eTH5D4QpXMacfTGaVqlF3pGqyIg7Wng
