### ISSUE TITLE
[테코톡] Node.js | 유세지

### ISSUE THREAD

**Issue by sojukang** [woowacourse/media#50]

**Comment by sojukang** [comment]
안녕하세요 `우연`👋!!!
유세지의 Node.js 편집 끝났습니다. 
앞, 뒤 자르는 것 빼고는 중간에 기침으로 끊은 부분만 편집했습니다.
[구글 드라이브 링크]( https://drive.google.com/drive/folders/1XSUf-Wnq2Qph5H7MPGJSOIxU12w3bEwl)
화이팅입니다👍👍👏

**Comment by ronci** [comment]
유세지 Node.js 편집 및 자막 완료했습니다!
https://drive.google.com/drive/folders/1XSUf-Wnq2Qph5H7MPGJSOIxU12w3bEwl
