### ISSUE TITLE
[우테뷰] 백엔드 리뷰어 닉, 소니 인터뷰 영상을 업로드한다.

### ISSUE THREAD

**Issue by OzRagwort** [woowacourse/media#59]
[구글 드라이브 링크](https://drive.google.com/drive/folders/19jsie6dgWwraWy435wycsLKk6TsM5c-3)

**Comment by woowabrie** [comment]
업로드 완료. 7월 5일 18시 공개로 설정해뒀습니다.
@OzRagwort @jinyoungchoi95 @sure-why-not 고생 많으셨어요~

https://www.youtube.com/watch?v=7uiHc6j-sVM

우테코 크루였던 닉, 소니의 인터뷰이니 영상이 공개된 후 전체 잡담 슬랙에 공유해주시면 더 좋을 것 같네요 ☺️
