### ISSUE TITLE
[테코톡] merge, rebase, cherry-pick | 오리, 코린

### ISSUE THREAD

**Issue by OzRagwort** [woowacourse/media#6]

**Comment by OzRagwort** [comment]
[편집 영상 위치](https://drive.google.com/drive/folders/14eTH5D4QpXMacfTGaVqlF3pGqyIg7Wng)
안녕하세요 [더즈](@ldk980130) !
편집이 완료되어서 코멘트 남겨요!
자막 부탁드릴게요! 😃

**Comment by ldk980130** [comment]
구글 드라이브에 자막 업로드 완료 했습니다!
