### ISSUE TITLE
[우테뷰] 근로팀 영상을 촬영한다

### ISSUE THREAD

**Issue by sure-why-not** [woowacourse/media#63]
## New 근로 인터뷰

우테코 브랜딩 근로팀을 소개합니다!
우테코 프롤로그 근로팀을 소개합니다!

### 기획 의도
- 크루들에서 새로운 근로팀이 어떤 일을 하는지 알리기 위함
- 외부에서 우테코 홍보/서비스가 어떻게 진행되는지 알리 위함

### 인터뷰 정보
- 인터뷰어 : 모집 예정 (하고 싶은 사람 많음)
- 인터뷰이 : 근로당 3명
- 촬영 시간 : 약 5분
- 장소 : 선릉/잠실 캠퍼스
- 우아한 Tech 유튜브 업로드 예정

### 질문
- 근로 회의하는 영상 촬영
- 해당 근로는 어떤 일을 하나요?
- 시간은 얼마나 소요되나요?
- 하면서 가장 즐거웠던 기억이 있나요?

**Comment by sure-why-not** [comment]
## 프롤로그 근로 인터뷰 촬영
인터뷰이 : 후이, 마르코
인터뷰어 : 호호

일시 : 7/20 (수)
영상 내용 : 질문, 회의 상황 영상 촬영

**Comment by jinyoungchoi95** [comment]
# 브랜딩 근로 인터뷰 촬영
인터뷰이 : 안, 어썸오, 토르
인터뷰어 : 로마, 야호

일시 : 7/19 (화)
영상 내용 : 질문, 회의 상황 영상 촬영
