### ISSUE TITLE
[테코톡] 싱글톤과 정적클래스 | 아서

### ISSUE THREAD

**Issue by sojukang** [woowacourse/media#8]

**Comment by sojukang** [comment]
[싱글톤과 정적클래스 편집본](https://drive.google.com/drive/folders/11_TpPSNp6cMxL-YaG5spwl3gc6_xRVKf)
안녕하세요 [후디](@devHudi) 👋
편집된 영상입니다. 중간에 말 끊김 등 딱히 편집이 필요한 부분이 없어서 앞, 뒤 자르기만 한 상태입니다.
잘 부탁드립니다👍

**Comment by devHudi** [comment]
구글 드라이브 동일한 디렉토리에 작업한 자막 `.srt` 파일로 업로드 하였습니다 😃
