### ISSUE TITLE
[테코톡] 앨버의 리액트 렌더링 최적화 편집 여부를 확인한다.

### ISSUE THREAD

**Issue by woowabrie** [woowacourse/media#81]
앨버의 리액트 렌더링 최적화 편집본이 드라이브에 없네요.
편집/자막 담당자가 우연으로 되어있어 어사인 드려요. 확인 부탁드려요.

**Comment by ronci** [comment]
올라간줄 알았는데 안 올라갔었네요... 내일까지 올리도록 하겠습니다!

**Comment by ronci** [comment]
https://drive.google.com/drive/folders/1nGEwNmoUzrrbewdDzi2y1Ux5LHuTyiwv

정상적으로 올라갔습니다!

**Comment by woowabrie** [comment]
@ronci 확인 감사합니다~
