### ISSUE TITLE
[우테뷰] 프론트엔드 리뷰어 로이, 아사 인터뷰 영상을 업로드한다.

### ISSUE THREAD

**Issue by OzRagwort** [woowacourse/media#85]
편집, 자막, 썸네일까지 완료되었습니다.  

업로드 부탁드립니다!

[드라이브](https://drive.google.com/drive/folders/1-2NaXAmuCu_yreScFgLH47FL9V1c3nVB)

**Comment by woowabrie** [comment]
<img width="964" alt="스크린샷 2022-07-26 오전 8 28 25" src="https://user-images.githubusercontent.com/94498253/180891555-46178066-f323-4c9a-b394-305f5aa4998e.png">

@wmakerjun 
준, 배경음 때문에 문제가 있는 듯 한데 이럴 때 어떻게 처리하셨나요?

**Comment by wmakerjun** [comment]
@woowabrie 
저작권 침해가 생기는 경우 해당 영상을 통해서 수익을 벌지 못하는 것뿐이니 채널이나 영상에는 영향이 없어서 걱정하지 않으셔도 됩니다~

**Comment by woowabrie** [comment]
https://www.youtube.com/watch?v=96Di62RvZJY

오늘 오후 6시에 공개하도록 설정했습니다.
