### ISSUE TITLE
[브이로그] 모락팀 브이로그를 업로드한다.

### ISSUE THREAD

**Issue by Byeongju-Kong** [woowacourse/media#94]
모락팀 브이로그 최종 편집 완료하였고 썸네일 만들었습니다!
`영상 근로 > 브이로그 > 모락vlog`에 파일 위치시켜 뒀습니다!

업로드 하시면 될 것 같습니다!!

**Comment by woowabrie** [comment]
수요일 18시 공개 설정 해놨습니다.
https://www.youtube.com/watch?v=sLBxjoZ6gKA
